apiVersion: v1
kind: Service
metadata:
  name: webapi
spec:
  type: NodePort
  selector:
    run: webapi
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000

---
apiVersion: v1
kind: Service
metadata:
  name: mssql
spec:
  type: NodePort
  selector:
    run: mssql
  ports:
  - name: mssql
    protocol: TCP
    port: 1433
    targetPort: 1433
    nodePort: 30001
