apiVersion: v1
kind: Service
metadata:
  name: webapi
spec:
  type: NodePort
  selector:
    run: webapi
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
