apiVersion: v1
kind: Service
metadata:
  name: k8slab-webapi
spec:
  type: NodePort
  selector:
    run: k8slab-webapi
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
