apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
spec:
  selector:
    matchLabels:
      run: webapi
  replicas: 1
  template:
    metadata:
      labels:
        run: webapi
    spec:
      initContainers:
        - name: webapi-init
          image: groundnuty/k8s-wait-for:v1.7
          imagePullPolicy: IfNotPresent
          args:
            - "job"
            - "ef-migration"
      containers:
        - name: webapi
          image: k8slab/webapi:latest
          imagePullPolicy: Never # Force load image locally to avoid pulling from public container registry
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Development"
          resources:
            limits:
              cpu: "250m"
              memory: "64Mi"
      # initContainers:
      #   - name: ef-migration
      #     image: k8slab/ef:latest
      #     command:
      #       [
      #         "sh",
      #         "-c",
      #         "/opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P MyPass@word -d k8slab.webapi -i /migrations.sql",
      #       ]
      #     imagePullPolicy: Never
