apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanagerconfig-slack
  namespace: monitoring # This AlertmanagerConfig will ONLY receive firing alerts from monitoring namespace
  labels:
    release: prometheus
spec:
  receivers:
    - name: slack
      slackConfigs:
        - sendResolved: true
          apiURL:
            key: apiSecret
            name: slack-webhook
          channel: '#alertmanager'
          title: >-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
          text: >-
            {{ range .Alerts -}}
            {{ if .Labels.severity }}`{{ .Labels.severity }}`{{ end }}

            *Description:* {{ .Annotations.description }}

            *Details:*
              {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
              {{ end }}
            {{ end }}
  route:
    receiver: slack
    repeatInterval: 1m
    groupInterval: 10s
    groupWait: 10s
    groupBy:
      - alertname
      - severity
    matchers:
      - name: severity
        value: warning|critical
        matchType: =~
      # - name: namespace   # Current namespace is automatically added as a matcher when alertmanger reads the config
      #   value: monitoring
