apiVersion: batch/v1
kind: Job
metadata:
  name: k8slab-ef-migration
spec:
  template:
    spec:
      containers:
        - name: k8slab-ef-migration
          image: k8slab/ef:latest
          imagePullPolicy: Never
          command: ["/bin/sh", "-c", "dotnet-ef database updates"]
      restartPolicy: Never
      #activeDeadlineSeconds: 10
  backoffLimit: 1
