apiVersion: batch/v1
kind: Job
metadata:
  name: ef-migration
spec:
  template:
    spec:
      containers:
        - name: ef-migration
          image: k8slab/ef:latest
          imagePullPolicy: Never
          command:
            [
              "sh",
              "-c",
              "/opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P MyPass@word -d k8slab.webapi -i /migrations.sql",
            ]
      restartPolicy: Never
      #activeDeadlineSeconds: 10
  backoffLimit: 1
