# Sample web app exposed on localhost:30000
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        vault.hashicorp.com/agent-inject: 'true' # Enables the vault agent injector service
        vault.hashicorp.com/role: 'internal-app' # The vault kubernetes authentication role
        vault.hashicorp.com/agent-inject-secret-database-config.txt: 'internal/data/database/config' # Writes selected kv secret to /vault/secrets/database-config.txt on pod 
    spec:
      serviceAccountName: internal-app
      containers:
        - name: nginx
          image: nginx:1.23.3
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
